### ISSUE TITLE
make snake taller by eating food

### ISSUE THREAD

**Issue by meandor** [DiscoverAI/snake#25]
when snake enters food tile -> food disappear and snake grow

**Comment by meandor** [comment]
introduce a direction matrix instead of vector so we always know where each token of the snake is heading for growing and stuff

**Comment by emilyagras** [comment]
My dear friend @dantoml and I have been working on this. We're going to make eating the food / making the food go away part of this, yeah?

**Comment by meandor** [comment]
@emilyagras  yeah
