### ISSUE TITLE
Game ends at 32 points

### ISSUE THREAD

**Issue by falcowinkler** [DiscoverAI/snake#32]
When you have 31 points, on eating the next apple the game will halt 🤔🤔🤔 nothing shows up in the logs

**Comment by falcowinkler** [comment]
so it's not exactly 31 points, sometimes also occurs on 28 or 31. random-vector crashes with index out of bounds.

**Comment by falcowinkler** [comment]
to reproduce (b/random-vector [24 24] [[8 23] [9 23] [10 23] [11 23] [12 23] [12 22] [12 21] [12 20] [12 19] [12 18] [12 17] [12 16] [12 15] [12 14] [12 13] [12 12] [12 11] [12 10] [12 9] [12 8] [12 7] [12 6] [12 5] [12 4] [12 3] [11 3] [10 3] [9 3] [8 3] [8 2] [8 1] [8 0]])

**Comment by meandor** [comment]
is this fixed already? if not it should be in to do i guess

**Comment by falcowinkler** [comment]
yes it is fixed

**Comment by falcowinkler** [comment]
if you want to review, the related code changes were in the random vector function in board.clj
