### ISSUE TITLE
Backend: Init State

### ISSUE THREAD

**Issue by falcowinkler** [DiscoverAI/snake#4]

**Comment by meandor** [comment]
State with:
* board size
* snake position
* snake direction
* speed for snake

**Comment by falcowinkler** [comment]
refer #7

**Comment by falcowinkler** [comment]
keep in mind we need to emit an initialised event (this can be part of the websockets card)

**Comment by meandor** [comment]
@falcowinkler TDD! test first, then red green refactor please and think more functional
