### ISSUE TITLE
Backend: Add rotation left, right to change direction of snake

### ISSUE THREAD

**Issue by meandor** [DiscoverAI/snake#8]
only rotation left right allowed

if t1 direction is [1 0], allowed new directions for t2 are only [0 -1]   and [0 1]
if t1 direction is [-1 0], allowed new directions for t2 are only [0 1]   and [0 -1]
if t1 direction is [0 1], allowed new directions for t2 are only [-1 0]   and [1 0]
if t1 direction is [0 -1], allowed new directions for t2 are only [1 0]   and [-1 0]

**Comment by falcowinkler** [comment]
see #10
